### ISSUE TITLE
Fails on start-up

### ISSUE THREAD

**Issue by jdc-cpt** [BlueGreenMagick/Image-Editor#29]
OS: Fedora Workstation 41
Anki Flathub, v24.11

Yesterday, when I opened up anki, the following bug report showed up. The app is now unusable on my anki version:
```
Anki 24.11 (87ccd24e) (src) (ao)
Python 3.11.10 Qt 6.7.3 PyQt 6.7.1
Platform: Linux-6.11.10-300.fc41.x86_64-x86_64-with-glibc2.38

When loading Image Editor:
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/aqt/addons.py", line 250, in loadAddons
    __import__(addon.dir_name)
  File "/home/jc/.var/app/net.ankiweb.Anki/data/Anki2/addons21/307397307/__init__.py", line 3, in <module>
    assert version.startswith("2.1.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
I realize this app hasn't been updated in a long time, but just wanted to post this in case anyone has a good solution or wants to fork this for a working version. Unfortunately, I am not a programmer myself.

**Comment by hhlp** [comment]
Mee too

OS: Fedora Workstation 41
Anki Flathub, v24.11

```python
Anki 24.11 (87ccd24e) (src) (ao)
Python 3.11.10 Qt 6.7.3 PyQt 6.7.1
Platform: Linux-6.12.4-200.fc41.x86_64-x86_64-with-glibc2.38

When loading Image Editor:
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/aqt/addons.py", line 250, in loadAddons
    __import__(addon.dir_name)
  File "/home/hhlp/.var/app/net.ankiweb.Anki/data/Anki2/addons21/307397307/__init__.py", line 3, in <module>
    assert version.startswith("2.1.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

Regards.,

**Comment by BlueGreenMagick** [comment]
Sorry, I don't plan on updating the add-on anymore.

That said, if you want to keep using it, you can patch `__init__.py` by removing the line `assert version.startswith("2.1")`, then change the next line to `minor_version = 70`. Then that error should go away.
