### ISSUE TITLE
Getting error on 2.1.41beta3

### ISSUE THREAD

**Issue by AnKingMed** [BlueGreenMagick/Image-Editor#6]
Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 526, in handler
  File "/Users/Nick/Library/Application Support/Anki2/addons21/307397307/annotation.py", line 141, in check_same_image_selected
    fld_txt = self.editor.note.fields[self.editor.currentField]
TypeError: list indices must be integers or slices, not NoneType

**Comment by BlueGreenMagick** [comment]
Fixed in v1.2!
